image: "python:3.6"

cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - .miniconda3/bin

tests:3.6:
  before_script:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p .miniconda3 -u
    - rm Miniconda3-latest-Linux-x86_64.sh
    - export PATH=".miniconda3/bin:$PATH"
    - hash -r
    - conda config --add channels bioconda
    - conda config --add channels conda-forge
    - conda config --set always_yes yes --set changeps1 no
    - conda env create -f environment.yml
    - source activate gnali-env
    - git clone --depth 1 https://github.com/konradjk/loftee.git loftee-grch37
    - git clone -b grch38 --depth 1 https://github.com/konradjk/loftee.git loftee-grch38
    - export LOFTEE_PATH_GRCH37="${PWD}/loftee-grch37"
    - export LOFTEE_PATH_GRCH38="${PWD}/loftee-grch38"
    - export HOME=$CI_BUILDS_DIR
    - bash ${PWD}/download_references.sh test
    - pip install tox
  variables:
    LOFTEE_PATH_GRCH37: $LOFTEE_PATH_GRCH37
    LOFTEE_PATH_GRCH38: $LOFTEE_PATH_GRCH38
  script:
    - tox -r -e py36

flake8:
  before_script:
    - pip install tox
  script:
    - tox -e flake8
