image: "python:3.6"

cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - .miniconda3/bin

tests:3.6:
  before_script:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p .miniconda3 -u
    - rm Miniconda3-latest-Linux-x86_64.sh
    - export PATH=".miniconda3/bin:$PATH"
    - hash -r
    - conda config --add channels bioconda
    - conda config --add channels conda-forge
    - conda config --set always_yes yes --set changeps1 no
    - conda env create -f environment-dev.yml
    - source activate gnali-env
    - export HOME=$CI_BUILDS_DIR
    - pip install tox
  script:
    - gnali_setup test
    - tox -r -e py36

flake8:
  before_script:
    - pip install tox
  script:
    - tox -e flake8
