name: gnali-env
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ensembl-vep=101.0=pl526hecda079_0
  - pybiomart=0.2.0=pyh864c0ab_1
  - pandas=1.1.3=py36h831f99a_0
  - numpy=1.19.2=py36he0f5f23_1
  - cython= 0.29.17=py36h90709c0_0
  - pysam=0.16.0.1=py36h71d3148_0
  - filelock=3.0.12=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36he6145b8_1
  - pip:
    - bgzip==0.3.5
    - .
