name: gnali-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - ensembl-vep=101
  - samtools
  - htslib
  - perl-bio-bigfile
  - pybiomart
  - pandas
  - numpy
  - pysam<0.16
  - filelock
  - pyyaml
  - py-bgzip
  - python-magic
  - progress
  - git>=2
  - cython
  - pip
  - pip:
    - bgzip==0.3.5
    - .
