name: gnali-env
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pysam<0.16
  - libcurl
  - ensembl-vep=101
  - perl-bio-bigfile
  - tabix
  - pandas
  - numpy
  - cython
  - filelock
  - pyyaml
  - pybiomart
  - py-bgzip
  - python-magic
  - progress
  - samtools
  - git>=2
  - pip
  - pip:
    - bgzip==0.3.5
    - .
