site_name: gNALI

theme: cinder
repo_url: "https://github.com/phac-nml/gnali"
copyright: "gNALI is licensed under the <a href='https://github.com/phac-nml/gnali/blob/master/LICENSE.txt'>Apache License Version 2.0</a><br>Copyright Government of Canada 2020-2021"

nav:
    - Home: index.md
    - News:
        - News: news.md
        - CHANGELOG: CHANGELOG.md
    - Install:
        - gNALI: install.md
    - Parameters: parameters.md
    - Examples:
        - Walkthrough (Simple): simple.md
        - Walkthrough (Advanced): advanced.md
    - Filtering: filtering.md

markdown_extensions:
  - toc:
        permalink: true

extra_css: [css/extra.css]
